### ISSUE TITLE
Adding a 'custom generate' option 

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#103]
I would like to add a button to the page that will generate flashing a light combination for random feasible input values. Please let me work on this issue!

**Comment by sk66641** [comment]
@Jasleen1210 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. 😊 Also this issue has already been addressed in issue #87
