### ISSUE TITLE
their to no proper feedback form to it

### ISSUE THREAD

**Issue by shivathmikavemula** [sk66641/Random-Disco-Light-Simulator#106]
Hello PA,
Their is no proper feedback form to it. I have added the feedback form to it and its in the pull request to mine.
 
### Screenshot: before
![Screenshot (21)](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/133566953/6ba22b13-7a68-4d5d-a970-0261a5188943)

### Screenshot : After adding the feedback form
![Screenshot (16)](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/133566953/81dfdae3-e574-4744-8153-b6a2b2dc79f0)

### then
![Screenshot (17)](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/133566953/281e249c-2675-4330-8bd6-10bd86a02616)

**Comment by shivathmikavemula** [comment]
I have done the task its in the pull request of mine. I request you to assign the gssoc level to it. @sk66641 
#106

**Comment by sk66641** [comment]
@shivathmikavemula 

Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. 😊
