### ISSUE TITLE
Feature: Spiral View

### ISSUE THREAD

**Issue by muskan42** [sk66641/Random-Disco-Light-Simulator#112]
I would like to add a spiral mode where lights move in a spiral pattern.
Kindly assign the issue under gssoc'24

**Comment by muskan42** [comment]
@sk66641 please assign the issue

**Comment by muskan42** [comment]
@sk66641 thankyou for assigning.

**Comment by muskan42** [comment]
@sk66641 I am having difficulty finding the code of the conic and radial view modes in the js or css files of the source code. 
It would be great if you could help.

**Comment by sk66641** [comment]
@muskan42 
It's inside the function named "applyRandomGradientPattern" in js file. You can search it in js file using "Ctrl+F"

**Comment by muskan42** [comment]
@sk66641 there are certain glitches I'm not able to fix in the code. 
I would request you to unassign me.
