### ISSUE TITLE
Improvement: On successful submission  appearance of popup box instead of alert message 

### ISSUE THREAD

**Issue by siya25097** [sk66641/Random-Disco-Light-Simulator#116]
Description:
Replace the alert message with a popup box upon successful submission to enhance the user experience with a more visually appealing and interactive notification.

 Feature Details:
1. Popup Design: A modal or popup box styled to match the website's theme.
2. Content: The popup box includes a success message, as well as note of reloading 
3. Visibility Trigger: The popup appears only after a successful submission.
4. User Interaction: The popup can be dismissed by the user via a close button or clicking outside the box.
 
@sk66641 please assign me this issue under gssoc'24

**Comment by sk66641** [comment]
@siya25097 
this issue is being solved in #105 . To keep our issue tracker organized, I will be closing this issue.

**Comment by Samik123Mit** [comment]
pls assign me ,i will commit changes in js to make a popup appear
