### ISSUE TITLE
Improvement: change alert box of are you sure you want to reload? to a popup box with yes and no option

### ISSUE THREAD

**Issue by siya25097** [sk66641/Random-Disco-Light-Simulator#117]
Description:
Replace the browser's default alert box for the "Are you sure you want to reload?" message with a custom popup box that provides a more user-friendly interface with "Yes" and "No" options.

Feature Details:
Popup Design: A custom modal styled to match the website's theme, ensuring a consistent look and feel.
Content: The popup contains a message asking if the user is sure they want to reload the page, along with "Yes" and "No" buttons.
Visibility Trigger: The popup appears when a reload action is initiated.
User Interaction: Users can confirm (Yes) or cancel (No) the reload action via the buttons.

Expected Behavior:
Initial State: No popup is visible when the page loads.
Reload Attempt: User attempts to reload the page.
Popup Appearance: Instead of the default alert, a custom popup box appears with the message "Are you sure you want to reload?".
User Decision:
Yes: If the user clicks "Yes," the page reloads.
No: If the user clicks "No," the popup closes, and the page remains unchanged.

@sk66641 please assign me this issue under gssoc'24

**Comment by sk66641** [comment]
@siya25097 
I have reopened this issue and assigned to you as in issue #117 , there was different issue being solved.

**Comment by Samik123Mit** [comment]
I will use js to make a pop up box would also ensure it works well ,pls assign me the issue

**Comment by sk66641** [comment]
@Samik123Mit 
We have removed this alert box. So, to keep our issue tracker organized, I will be closing this issue.
