### ISSUE TITLE
[BUG] : Icon is not in center in footer

### ISSUE THREAD

**Issue by dhruv8433** [sk66641/Random-Disco-Light-Simulator#119]
@sk66641 

check this out,
when we hover on footer icons

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/114583978/11403b16-3c7a-403c-b8fb-e52e9c010106)

we can display those icons in center while hover it

**Comment by sk66641** [comment]
@dhruv8433 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. 😊
