### ISSUE TITLE
Adding "Contact" details

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#122]
The website's absence of Contact Information is noted. Introducing a Contact Information box containing relevant details would greatly enhance user interaction and communication. 

As a GSSoC'24 contributor, I'm eager to tackle this issue.

 Thank you!

**Comment by sk66641** [comment]
@AkshitGarg24 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. 😊
