### ISSUE TITLE
Make the site responsive!

### ISSUE THREAD

**Issue by sk66641** [sk66641/Random-Disco-Light-Simulator#123]
I've noticed that the site isn't fully responsive, especially when it comes to the footer and navbar. Enhance the user experience by making these elements adapt seamlessly across different devices.

**Comment by AkshitGarg24** [comment]
@sk66641  Please assign this issue to me. I will take care of making the website responsive.

 Thank you!

**Comment by AkshitGarg24** [comment]
@sk66641 Could you please provide more details on how you would like your navbar and footer to appear once they are made responsive? Currently, I notice that the navbar wraps the content when the width decreases.

**Comment by sk66641** [comment]
@AkshitGarg24 
you can place the navbar in the header section as i have marked in the attached image and 
for footer, reduce the gap between icons & 
make this text  "©2024 Random-Disco-Light-Simulator. All rights reserved."  smaller for smaller devices &
also remove that white line, marked in the attached image
![img](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/8514ac43-9198-4eae-9c41-e5e06fd308a7)

**Comment by AkshitGarg24** [comment]
@sk66641 should the navbar be placed in the header section for all devices or only for small devices? Similarly confirm the same for the white line in the footer.

**Comment by sk66641** [comment]
@AkshitGarg24 
I have updated the previous comment now

> @AkshitGarg24
> 
> **For all devices:**
> 
> 1. Place the navbar in the header section as i have marked in the attached image
> 2. Remove that white line, marked in the attached image
> 
> **For smaller devices:**
> 
> 1. For footer, reduce the gap between icons
> 2. Make this text  "©2024 Random-Disco-Light-Simulator. All rights reserved."  smaller
>    ![img](https://private-user-images.githubusercontent.com/145834771/336191546-8514ac43-9198-4eae-9c41-e5e06fd308a7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NDE4MDMsIm5iZiI6MTcxNzQ0MTUwMywicGF0aCI6Ii8xNDU4MzQ3NzEvMzM2MTkxNTQ2LTg1MTRhYzQzLTkxOTgtNGVhZS05YzQxLWU1ZTA2ZmQzMDhhNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QxOTA1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2M0OGFiYzFmZjhjN2NlOGFmYzNkMjRhY2U1ZmU5ZTY2OTFkZmYzNjRiYzI1NWIwMTYwYzY0ZDdmZDNjZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8z1hH9s2O2n-btVZkxlIarHtZm3Ak5_RF_NKo5YAJas)

**Comment by Samik123Mit** [comment]
Please assign me the issue. I will make sure that the site is fully responsive and suitable for all devices.

**Comment by Samik123Mit** [comment]
Please assign me the issue. I will make sure that the site is fully responsive and suitable for all devices.
