### ISSUE TITLE
Creating a navbar to make the sections clearly visible

### ISSUE THREAD

**Issue by Shreesanyog** [sk66641/Random-Disco-Light-Simulator#128]
The current design of the project lacks a clear distinction between the header and the content. To address this, I propose implementing a navbar that visually separates the header elements from the body content.

In below screenshot we can see that the sections- About, features, light mode, dark mode  lacks clear distinction from other content.

<img width="630" alt="image" src="https://github.com/sk66641/Random-Disco-Light-Simulator/assets/166977453/f771727b-136b-4b67-9a63-f2c34a43e0af">

Please assign this to me under gssoc

**Comment by sk66641** [comment]
@Shreesanyog 
We have already identified this issue, and it is currently being addressed in #123. You can follow the progress and participate in the discussion there.
To keep our issue tracker organized, I will be closing this issue.
