### ISSUE TITLE
feat: adding feedback section

### ISSUE THREAD

**Issue by solanki505** [sk66641/Random-Disco-Light-Simulator#134]
feedback is important feature to know the suggestion of the users, using this site. I would like to add a feedback icon  in the home page section which will direct  us to a feedback page
![Screenshot 2024-06-02 175155](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/158484284/b6fe82ad-1704-4dc6-b155-5f2264c7d471)

**Comment by sk66641** [comment]
@solanki505 
also remove this comment section or replace it with feedback form
![img](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145834771/0dd82e13-2b30-450f-932e-d9881ca25d45)
