### ISSUE TITLE
Corrections in contributing.md file

### ISSUE THREAD

**Issue by PradnyaGaitonde** [sk66641/Random-Disco-Light-Simulator#139]
There are a few necessary corrections to be made in the contributing.md file.
Please assign this issue to me under gssoc24.

**Comment by sk66641** [comment]
@PradnyaGaitonde 
Can you explain the kind of corrections needed?

**Comment by PradnyaGaitonde** [comment]
@sk66641 In the github contribution instructions in contributing.md file, the repository name in most of the places is wrong. Would like to replace it.

**Comment by sk66641** [comment]
@PradnyaGaitonde 
where is it wrong ? Can you paste a screenshot?

**Comment by PradnyaGaitonde** [comment]
@sk66641 also in the 9th point as well

**Comment by sk66641** [comment]
@PradnyaGaitonde 
I've assigned this issue to you.
