### ISSUE TITLE
Text and UI/UX improvement

### ISSUE THREAD

**Issue by muskan42** [sk66641/Random-Disco-Light-Simulator#140]
The text of the form seems too congested. I had like to improve it along with the text styling, animation and UI/UX of the form.
@sk66641 kindly assign the issue to me under gssoc'24

**Comment by sk66641** [comment]
@muskan42 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment as there are already too many issues  being addressed on UI/UX . If you have any additional issues, feel free to reach out. 😊
