### ISSUE TITLE
Enhance Footer Display

### ISSUE THREAD

**Issue by muskan42** [sk66641/Random-Disco-Light-Simulator#141]
@sk66641 I would like to enhance the display of the footer and the way it pops up while scrolling down.
Allow me to help resolve the issue.

**Comment by sk66641** [comment]
@muskan42 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment as there are already too many issues being addressed on UI/UX like #92 . If you have any additional issues, feel free to reach out. 😊
