### ISSUE TITLE
Add Customizable Presets🚨

### ISSUE THREAD

**Issue by animex007** [sk66641/Random-Disco-Light-Simulator#143]
## Description: 
Allow users to save their current settings (color quantity, time interval, view type, and sound effects) as presets that can be easily reloaded.

### Benefits:

*Convenience* : Users can quickly switch between their favorite settings without having to manually adjust them each time.
*Personalization* :  Users can create and manage multiple presets for different moods or events.

**This feature would make the Random Disco Light Simulator more versatile and user-friendly, enhancing its appeal and functionality.**

### *please assign me this issue to work on it*

**Comment by thevijayshankersharma** [comment]
@sk66641 Hey, I would like to do this.

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/109781385/434bfe4f-9df3-44f6-9afd-d1412dbc7547)

**Comment by sk66641** [comment]
@animex007 
Could you please give an update over this issue as it has been pending for over two weeks?

**Comment by animex007** [comment]
On the way  ! I will upload the PR ASAP
