### ISSUE TITLE
Adding SCROLL TO TOP button

### ISSUE THREAD

**Issue by MuraliDharan7** [sk66641/Random-Disco-Light-Simulator#146]
There is not scroll to top button on existing page. I can add the same. Whenever there is a website that would have that button to take us to top of the web.

Please assign this issue to me under GSSoC'24.

**Comment by sk66641** [comment]
@MuraliDharan7 
We have already identified this issue, and it is currently being addressed in #114 . You can follow the progress and participate in the discussion there.
To keep our issue tracker organized, I will be closing this issue.
