### ISSUE TITLE
Adding Examples for features

### ISSUE THREAD

**Issue by MuraliDharan7** [sk66641/Random-Disco-Light-Simulator#147]
There is not example to explain how the feature going to be. I can add screenshot to explain what that particular feature do.

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/130668745/f5f7a3af-098a-4631-9447-71fa7667bcf7)

Assign this issue to me under GSSoC'24. Add relevant labels into it.

**Comment by Samik123Mit** [comment]
pls assign me the issue ,i will make sure that the task is done .
