### ISSUE TITLE
Made site more attractive  by making some changes in css

### ISSUE THREAD

**Issue by piyushsahujtp** [sk66641/Random-Disco-Light-Simulator#148]
I want to make timer more effective with shadow and look clear.
Make some changes in background of the buttons.
I want to add more customised buttons and easy to understand language.

**Comment by Kat-o30** [comment]
I would like to work on this project . Please assign it to me .

**Comment by piyushsahujtp** [comment]
How to contribute

**Comment by Samik123Mit** [comment]
I would make the styling better by making it visually appealing and would enhance the presence by diversifying the color palette and would make it look attractive.

**Comment by sk66641** [comment]
@piyushsahujtp 
To know about contributing to our project or any project, you can checkout [Learn.md](https://github.com/sk66641/Random-Disco-Light-Simulator/blob/main/Learn.md)

**Comment by thevijayshankersharma** [comment]
@sk66641 Assign this too if he is inactive.

**Comment by sk66641** [comment]
@piyushsahujtp 
Could you please give an update over this issue as it has been pending for over two weeks?

**Comment by piyushsahujtp** [comment]
I'm working on it .

**Comment by piyushsahujtp** [comment]
Yes, I am working on it.

**Comment by sk66641** [comment]
PR #264 by @piyushsahujtp  for this issue was not valid and it seems that no further action is needed at the moment as there has already been so many changes in the css file that has resolved this issue.

**Comment by piyushsahujtp** [comment]
Ok, thanks for the update.
