### ISSUE TITLE
ENHANCE Readme FILE

### ISSUE THREAD

**Issue by piyushsahujtp** [sk66641/Random-Disco-Light-Simulator#149]
Describe the bug ✍️
I would like to enhance the Readme file to make it more precise.

Provide step by step information reproduce the bug 📄
I would like to create add seperate sections for tech stack, code of conduct, screenshot of the project, project admin details and contributors details

**Comment by sk66641** [comment]
@piyushsahujtp 
Thank you for raising this issue however I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.

**Comment by piyushsahujtp** [comment]
I think its important to make some changes in readme file for better understanding about the project by contributors so , kindly reassign me the project.

**Comment by sk66641** [comment]
@piyushsahujtp 
ok
