### ISSUE TITLE
Turn Off text selection in website

### ISSUE THREAD

**Issue by SuhainaFathimaM** [sk66641/Random-Disco-Light-Simulator#157]
Turn Off text selection in website
text selection has to be turned off

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153417476/ea803b07-bae5-4587-8e61-b081d9589226)

@sk66641 I would like to work on this issue. I am a GSSoC Contributor

**Comment by rohir1132yadav** [comment]
i want to work on this project .please assign me

**Comment by thevijayshankersharma** [comment]
@sk66641 Assign this too if he is inactive.

**Comment by sk66641** [comment]
@SuhainaFathimaM 
Could you please give an update over this issue as it has been pending for over two weeks?

**Comment by sk66641** [comment]
@thevijayshankersharma 
issue assigned

**Comment by sk66641** [comment]
@thevijayshankersharma 
@SuhainaFathimaM has sent a PR #281 for this issue now as she was busy in their exams & also there was a mistake from my side as i didn't see @rohir1132yadav has commented earlier asking for the same.

**Comment by sk66641** [comment]
@thevijayshankersharma 
For this, i've assigned level3 to your PR #267

**Comment by thevijayshankersharma** [comment]
> @thevijayshankersharma For this, i've assigned level3 to your PR #267. If you have any additional issues, feel free to reach out.

No, not a problem.
