### ISSUE TITLE
add style to the cursor

### ISSUE THREAD

**Issue by gangwarsomya** [sk66641/Random-Disco-Light-Simulator#162]
want to add a rainbow effect to the cursor

**Comment by RamakrushnaBiswal** [comment]
Hi @sk66641 can I work upon it

**Comment by thevijayshankersharma** [comment]
I would like to work too.

**Comment by aditya-bhaumik** [comment]
@sk66641 hi i had a created a issue related to this in #196 you had said you will assign it to me if the he/she is inactive for more than 5 days 

Can you please open that issue and assign to me please

**Comment by anshikatiwari20** [comment]
@sk66641 I am a GSSoC contributor and would like to work on issue #162 to add style to the cursor as requested. Could you please assign this issue to me? Thank you!

**Comment by sk66641** [comment]
@gangwarsomya 
Could you please give an update over this issue as it has been pending for over two weeks?

**Comment by gangwarsomya** [comment]
@sk66641 i'm facing problem in creating pr give me one i'll  fix this.
sorry for the inconvenience
