### ISSUE TITLE
Grammar and Phrasing Improvements in Inputs Section

### ISSUE THREAD

**Issue by ishap11** [sk66641/Random-Disco-Light-Simulator#164]
Hello, my name is Isha Prajapati.
I noticed some small grammar and phrasing issues in the Inputs section of our documentation. Here are the changes I'd like to make:

Current: "How many random colors you want to be shown?"
Proposed: "How many random colors do you want to be shown?"

Current: "Select your desired start & end colors for the gradient"
Proposed: "Select your desired start & end colors for the gradient."

Current: "With how much time interval (in milliseconds) you want to change the colors randomly?"
Proposed: "With what time interval (in milliseconds) do you want to change the colors randomly?"

Current: "What type of view you want to choose (conic, linear or radial)?"
Proposed: "What type of view do you want to choose (conic, linear, or radial)?"

Current: "Countdown timer (in seconds)"
Proposed: "Set the countdown timer (in seconds)."

![Screenshot 2024-06-05 163044](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/128213933/5a483fe5-faff-4540-adb4-3778c5df96f3)

I'm eager to contribute under GSSOC'24 and would like to request the assignment of this task.
Thank you!

**Comment by ishap11** [comment]
I've submitted a new pull request with the changes I've made. Please take a look and review it.
 " Resolved Issues in the Inputs Section #1 "
Thank you!

**Comment by sk66641** [comment]
> I've submitted a new pull request with the changes I've made. Please take a look and review it. " Resolved Issues in the Inputs Section #1 " Thank you!

@Coding-whiz 
Can you guide him @ishap11 ? She has sent a pull request in her forked repository.

**Comment by Coding-whiz** [comment]
Hi,

If it isn't urgent may I look into this after 10pm today?I am quite busy
right now.

Do let me know if it is urgent.

**Comment by sk66641** [comment]
> Hi, If it isn't urgent may I look into this after 10pm today?I am quite busy right now. Do let me know if it is urgent.


ok

**Comment by sk66641** [comment]
@ishap11 
To know more about creating a pull request, you can checkout [Learn.md](https://github.com/sk66641/Random-Disco-Light-Simulator/blob/main/Learn.md)

**Comment by ishap11** [comment]
Thanks! I’ll check out the Learn.md file.

**Comment by ishap11** [comment]
Hello @sk66641 and @Coding-whiz,
I noticed that the pull request for the README enhancements was closed but not merged. Could you please provide some feedback on what needs to be improved or why it wasn't merged?

I am eager to learn and make the necessary changes to contribute effectively.
Thank you for your guidance and support!

**Comment by sk66641** [comment]
@ishap11 
you have again created a PR in your forked repository! So, how can i merge it.

**Comment by ishap11** [comment]
Thank you for reopening the issue. I've created a PR in the main repository for your review. Please let me know if any changes are needed.
