### ISSUE TITLE
Improve Font

### ISSUE THREAD

**Issue by nimitagarwal26** [sk66641/Random-Disco-Light-Simulator#170]
I would love to give the website an appealing font as the current font does not look attractive. I will change the font type and its colors and make it more appealing. Please assign it to me under GSSoC'24 and don't forget to add level to the issue.

**Comment by sk66641** [comment]
@nimitagarwal26 
We have already identified this issue, and it is currently being addressed in #148. You can follow the progress and participate in the discussion there.
To keep our issue tracker organized, I will be closing this issue.
