### ISSUE TITLE
Documentation Fix

### ISSUE THREAD

**Issue by nimitagarwal26** [sk66641/Random-Disco-Light-Simulator#171]
The documentation does not contain the technology used section. A good documentation must contain what all techs are being used in the project.
I would love to fix this documentation issue. Please assign it to me under GSSoC'24 and please add level to the issue.

**Comment by sk66641** [comment]
@nimitagarwal26 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
