### ISSUE TITLE
feature : Adding icons in Home ,feature , light mode and dark mode

### ISSUE THREAD

**Issue by SadafKausar2025** [sk66641/Random-Disco-Light-Simulator#172]
Adding icons will give more visibility to the users

**Comment by sk66641** [comment]
@SadafKausar2025 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
