### ISSUE TITLE
Bug: The Box is Not visible properly to submit down

### ISSUE THREAD

**Issue by SadafKausar2025** [sk66641/Random-Disco-Light-Simulator#173]
at first it was difficult for me to submit because the button was not visible
I want to fix the box fully and good looking

**Comment by SadafKausar2025** [comment]
hello @sk66641 
can you please assign me this issue?

**Comment by sk66641** [comment]
@SadafKausar2025 
you can scroll down to submit.

**Comment by sk66641** [comment]
@SadafKausar2025 
This issue has been resolved. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
