### ISSUE TITLE
[Feat]: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [sk66641/Random-Disco-Light-Simulator#18]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/115717746/c9ad5201-d453-4e8a-bdeb-3f0980e616ba)

**Comment by Asymtode712** [comment]
@sk66641 can you please change the label name it must be **'level2'** instead of **'label2'**

Thank you!

**Comment by sk66641** [comment]
Oops, let me change. Thanks!
