### ISSUE TITLE
✨✨[FEAT]: add preview button for the music

### ISSUE THREAD

**Issue by rashiranjan22** [sk66641/Random-Disco-Light-Simulator#184]
users should be able to preview the audio the are selecting before submitting
@sk66641 kindly assign this issue to me under gssoc'24

**Comment by aditya-bhaumik** [comment]
@sk66641 can i work on this issue if he/she is inactive

**Comment by sk66641** [comment]
@rashiranjan22 
Could you please give an update over this issue as it has been pending for over three weeks? otherwise @aditya-bhaumik will be assigned..

**Comment by rashiranjan22** [comment]
@sk66641 , i apologise for being this late , was a bit busy in exams , would make a PR within 2-3 days
