### ISSUE TITLE
Adding styles to feature pop up

### ISSUE THREAD

**Issue by SuhainaFathimaM** [sk66641/Random-Disco-Light-Simulator#190]
Adding styles to feature pop up

@sk66641 I would like to work on this issue

**Comment by sk66641** [comment]
@SuhainaFathimaM 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
