### ISSUE TITLE
Very less number of options for choosing colour and colours are not attractive.

### ISSUE THREAD

**Issue by piyushsahujtp** [sk66641/Random-Disco-Light-Simulator#191]
I want to provide user a lot of options for chosing colour , assign me this project to make changes in the file.

**Comment by sk66641** [comment]
@piyushsahujtp 
Can you explain this issue once? or you are talking about the second input?

**Comment by piyushsahujtp** [comment]
> Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊
> 
> You can also check our [CONTRIBUTING.md](https://github.com/sk66641/Random-Disco-Light-Simulator/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

I want made some additional features like  adding an option for choosing more and more colours, button for restart the game and more additional features.

**Comment by sk66641** [comment]
@piyushsahujtp 
Could you please provide me with the details for all those features?

**Comment by piyushsahujtp** [comment]
I want to add a feature in which user swith to light mode and dark mode and along with it user manage the sound volute as per their need , They can save screenshot using a screenshot button on the top .

**Comment by sk66641** [comment]
@piyushsahujtp 
Thank you for raising this issue. We've reviewed it, and it seems that some of the features are already there like changing theme & issues have been created & assigned for other features. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
