### ISSUE TITLE
FEATURE: Make the Navbar look more attractive.

### ISSUE THREAD

**Issue by Vibhu315** [sk66641/Random-Disco-Light-Simulator#194]
Hello, this is Vibhu Patel,
I hope you're doing well. I'm interested in improving our website's functionality.

We can make the navigation bar look more attractive, using vibrant colors, adding hover effects, using stylish fonts.
I am eager to contribute under GSSoC'24 and help enhance our website’s functionality and user experience. Please assign this task to me.
Thank you!

**Comment by sk66641** [comment]
@Vibhu315 
Thank you for raising this issue but now it has placed inside menu. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
