### ISSUE TITLE
[Enhancement ] : Adding effects to the cursor

### ISSUE THREAD

**Issue by aditya-bhaumik** [sk66641/Random-Disco-Light-Simulator#196]
I will enhance the cursor effect on the website by adding a glowing effect to it. This change aims to make the cursor more visually appealing and interactive for users. Additionally, I may explore other cursor effects

**Comment by sk66641** [comment]
@aditya-bhaumik 
This issue is currently being addressed in #162. You can follow the progress and participate in the discussion there. 
I'll assign you if he/she gets inactive for 5+ days.
To keep our issue tracker organized, I will be closing this issue.
