### ISSUE TITLE
Full screen updation

### ISSUE THREAD

**Issue by dishathakurata** [sk66641/Random-Disco-Light-Simulator#197]
Whenever in full screen, the footer comes in the same page as the main content which looks unappealing and distracting. I can make footer in the next page and on the first page only the main content will be there.

![full screen](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/146114938/58b67adc-055a-4cb8-a049-6c4951c48a65)

My code is ready, I'm waiting for this issue to be assigned to me.
Please assign this issue to me under GSSoC.

**Comment by sk66641** [comment]
@dishathakurata 
We have already identified this issue, and it is currently being addressed in #179. You can follow the progress and participate in the discussion there. We'll assign this issue to you, if he/she gets inactive for 5+ days.  To keep our issue tracker organized, I will be closing this issue.
