### ISSUE TITLE
Scrollable content updation

### ISSUE THREAD

**Issue by dishathakurata** [sk66641/Random-Disco-Light-Simulator#199]
The content is needed to scroll to use, which is not user friendly. I can make the whole content in a single page which does not need scrolling, hence enhancing user-friendliness and easy to use.

![scroll](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/146114938/77d79243-86b7-48cb-894f-acf29329a05f)

Assign this issue to me under GSSoC.
My code is ready, I'm just waiting for this issue to be assigned to me.

**Comment by sk66641** [comment]
@dishathakurata 
This issue has already been resolved. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
