### ISSUE TITLE
Add Contribution.md

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [sk66641/Random-Disco-Light-Simulator#2]
Hey @sk66641  ,
To streamline the contribution process and make it easier for new contributors to get involved, it's important to have clear and detailed contribution guidelines. A CONTRIBUTING.md file outlines the steps and best practices for contributing to the project, ensuring consistency and high-quality contributions.
Please assign me this issue

**Comment by sk66641** [comment]
Hey, @Santhosh-Siddhardha Do you want to add CONTRIBUTE.md file or should i assign it to someone else?

**Comment by Santhosh-Siddhardha** [comment]
@sk66641 I will raise PR by evening
