### ISSUE TITLE
Improvement: Improve styling of all the buttons

### ISSUE THREAD

**Issue by siya25097** [sk66641/Random-Disco-Light-Simulator#201]
Hey, @sk66641 I would like to improve styling of all buttons where I can make it 3D button like given examples. Please assign me this under GSSOC'24.
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/6758ff78-4e59-48e3-817e-8ce79c4682dc)
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/10613849-ef5a-4f55-bc2b-1a93234f56bd)
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/42a6b00a-059c-41f2-9867-30531dd41996)

**Comment by sk66641** [comment]
@siya25097 
The third one looks better. I'm assigning this to you.
