### ISSUE TITLE
Improvement: styling of sidebar in both pages  

### ISSUE THREAD

**Issue by siya25097** [sk66641/Random-Disco-Light-Simulator#202]
Hey @sk66641, Sidebar in both the pages need more styling for smooth user experience. Please assign me this under GSSOC'24
Thank you.

**Comment by sk66641** [comment]
@siya25097 
Can you explain this issue once?

**Comment by siya25097** [comment]
@sk66641 i can make it something like this matching with the basic theme of the project
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/4114a24a-8745-43b5-8608-5f6d8f73c954)
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/f340df2d-386c-4d89-9b23-227211d66b9a)
