### ISSUE TITLE
Adding style to social handles bar and footer

### ISSUE THREAD

**Issue by bheemajayashreee** [sk66641/Random-Disco-Light-Simulator#208]
In the light theme, the social handles bar, footer has no border-radius added to it and the bar looks lengthy compared to the Spectrum box.

1. Go to 'Random disco light Simulator'
2. Click on 'Theme button'
3. Scroll down to 'bottom of the page'
4. You will find that the social handles bar and the footer are very improper.

**Expected behavior**
The social handle icons should be displayed like they are displayed in dark theme.

https://sk66641.github.io/Random-Disco-Light-Simulator/#

**Comment by bheemajayashreee** [comment]
Please assign this issue to me

**Comment by bheemajayashreee** [comment]
Please assign this issue to me!

**Comment by sk66641** [comment]
@bheemajayashreee 
We have already identified this issue, and it is currently being addressed in #176 . You can follow the progress and participate in the discussion there. We'll assign this issue to you, if he/she gets inactive for 5+ days.
To keep our issue tracker organized, I will be closing this issue.
