### ISSUE TITLE
padding , font-size and font-weight

### ISSUE THREAD

**Issue by Ancha2003** [sk66641/Random-Disco-Light-Simulator#21]
Can reduce the size of texts
You can improve the color of submit and reset buttons.
and also font weight

**Comment by pahuja-sahil** [comment]
@sk66641 hello there, I would like to work on this issue. I have already built a blogging website and github link of which is given below for reference, I can easily modify the form and efficiently do some meaningful changes like changing the background using a gradient color and adding some padding and giving some hover effects. I would like you to assign this issue under gssoc level2 .
link - https://github.com/pahuja-sahil/Online-Blogging-System
Kindly reply to this message.
Thank you.

**Comment by sk66641** [comment]
this issue has already been raised and assigned in issue #7, will have to wait:)
