### ISSUE TITLE
Add the glowing cursor

### ISSUE THREAD

**Issue by namandude** [sk66641/Random-Disco-Light-Simulator#217]
Hey i would like to add the glowing cursor in the site so that users feel more animistic and add the next level in the website 

Something like this or can change what best suites in the site .
![Screenshot 2024-06-08 025235](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/118013565/bddb261c-e838-49e2-aa8e-e8314280dbf4)

Please assing this to me under Gssoc i would like to work upon this,.
Thank you

**Comment by sk66641** [comment]
@namandude 
This issue is currently being addressed in #162. You can follow the progress and participate in the discussion there. We'll assign this issue to you, if he/she gets inactive for 5+ days.
To keep our issue tracker organized, I will be closing this issue.
