### ISSUE TITLE
Adding the logo 

### ISSUE THREAD

**Issue by namandude** [sk66641/Random-Disco-Light-Simulator#218]
Hey i would like to add the logo in the website  .
Please assign thsi to me under gssoc i m really wants to adds on in it .
Thank You!!

**Comment by sk66641** [comment]
@namandude 
Thank you for raising this issue. Since this issue has been solved in PR #226, To keep our issue tracker organized, I will be closing this issue.  If you have any additional issues, feel free to reach out.
