### ISSUE TITLE
Aligning the background color according to theme change

### ISSUE THREAD

**Issue by swetha5157** [sk66641/Random-Disco-Light-Simulator#224]
**Describe the bug**

- The Random Disco Light simulator has theme enabled as dark and light.
- The dark theme is well aligned with other div containers.
- But the background of the socials section is not aligned with the light theme.

**To Reproduce**
1. Go to the Random Disco Light Simulator page
2. Click on toggle theme as Light theme 
3. Scroll down to socials section
4. See the background is black when the theme is light.

**Expected behavior**
Making the desired changes in CSS of light theme and div container of socials, the light theme would be well aligned with the background.

**Screenshots**
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/123291594/53680bb5-4727-498a-a6bc-e90b332481a5)

**Additional context**
I am a GSSoc'24 contributor.
Kindly assign to me @swetha5157.

**Comment by sk66641** [comment]
@swetha5157 
This has been fixed in the PR #243. So, to keep our issue tracker organized, I will be closing this issue.
