### ISSUE TITLE
Making feature section more creative

### ISSUE THREAD

**Issue by MuraliDharan7** [sk66641/Random-Disco-Light-Simulator#233]
**Is your feature request related to a problem? Please describe.**
I just want to add the border and line breaks for each category and the font style for features section.

**Describe the solution you'd like**
I can add the visually appealing border and good font for features, also to add hover to the images in features section

**Additional context**
Please assign this me under GSSoC'24.

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/130668745/2334b60b-9aa3-4ea2-bff2-d1c0a61289aa)

**Comment by sk66641** [comment]
@MuraliDharan7 
This issue is currently being addressed in #232. You can follow the progress and participate in the discussion there.
To keep our issue tracker organized, I will be closing this issue.
