### ISSUE TITLE
Footer Section Needs Customization

### ISSUE THREAD

**Issue by MastanSayyad** [sk66641/Random-Disco-Light-Simulator#237]
Hey @sk66641 the footer section is need to get customized as you can see it has marginal and padding issues while being in Light mode

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101971980/1da36090-9de9-436f-9cbe-c8e90a3b570a)

I would like to take on this task could you please assign this issue to me under gssoc?

**Comment by sk66641** [comment]
@MastanSayyad 
This has been fixed in the PR https://github.com/sk66641/Random-Disco-Light-Simulator/pull/243. To keep our issue tracker organized, this issue will be closed.
