### ISSUE TITLE
Add a Better "Feedback Form"

### ISSUE THREAD

**Issue by MastanSayyad** [sk66641/Random-Disco-Light-Simulator#238]
Hey @sk66641 I would like to add a new feedback form 
as you can see the current one is not much visually appealing 

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101971980/2124e5b8-7a3c-4414-b4f6-b773e87cb231)

Could you please assign this issue to me under gssoc?

**Comment by dhruvishah85** [comment]
Hey @sk66641 I would like to contribute in this section of the project. I am eager to get started. Specifically, I am interested in working on feedback section.

Could you please assign this task to me i would try to give my best.

Thank you for considering my request. I am excited about the possibility of collaborating with you.
