### ISSUE TITLE
Improvement required in the footer section.

### ISSUE THREAD

**Issue by Braj-01** [sk66641/Random-Disco-Light-Simulator#241]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Braj-01** [comment]
Please assign me this task so that I can work on it under GSSOC'24.

**Comment by Braj-01** [comment]
Please assign me this task so that I can make required changes under GSSOC'24

**Comment by sk66641** [comment]
@Braj-01 
This has been fixed in the PR https://github.com/sk66641/Random-Disco-Light-Simulator/pull/243. To keep our issue tracker organized, this issue will be closed.
