### ISSUE TITLE
Feature: add a toggle fullscreen button

### ISSUE THREAD

**Issue by sk66641** [sk66641/Random-Disco-Light-Simulator#25]
### Feature

Users often need to switch to fullscreen mode for a better viewing experience. Adding a dedicated toggle fullsceen button will improve the user experience by allowing quick access to fullscreen mode.

### Additional details

- A button labeled 'Fullscreen' or with a fullscreen icon is to be added.
- Clicking the button toggles between fullscreen and normal mode.
- If it's a button, then it should show the current state (e.g., "Exit Fullscreen" when in fullscreen mode).
- It should be compatible with all the browsers.

**Comment by aditya-bhaumik** [comment]
@sk66641 can you please assign me this issue

**Comment by aditya-bhaumik** [comment]
@sk66641  i have added the toggle fullscreen button can you please assign me this issue so i can create a pull request

**Comment by lassmara** [comment]
please assign me this issue
