### ISSUE TITLE
Enhancement of About Section

### ISSUE THREAD

**Issue by harinisayani** [sk66641/Random-Disco-Light-Simulator#251]
**Is your feature request related to a problem? Please describe.**
I have observed that About section is not attractive.

**Describe the solution you'd like**
I want to make it more attractive by changing font and adding CSS features to it.

**Additional context**
I am GSSOC'24 contributor.
Please assign me this issue.

**Comment by sk66641** [comment]
@harinisayani 
Thank you for raising this issue. We've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
