### ISSUE TITLE
Add Scroll Bar on the page and add footer section

### ISSUE THREAD

**Issue by GitNinja-bcd** [sk66641/Random-Disco-Light-Simulator#252]
We can also add a scroll bar and instead of social media icons on the page we can add a footer section and then we can add those icons with more features.

**Comment by sk66641** [comment]
@GitNinja-bcd 
Thank you for raising this issue. We've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
