### ISSUE TITLE
feat: Adding custom pointer/cursor in the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [sk66641/Random-Disco-Light-Simulator#254]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by sk66641** [comment]
@RamakrushnaBiswal 
Could you please explain this issue once?

**Comment by RamakrushnaBiswal** [comment]
https://github.com/sk66641/Random-Disco-Light-Simulator/assets/125277258/5404da82-c8c7-4cb9-bab3-aa3692a447fc

we can change the cursor style like the video

**Comment by sk66641** [comment]
@RamakrushnaBiswal 
This issue has already been identified & is currently being addressed in #162 . You can follow the progress and participate in the discussion there. You can comment there to get assigned if the assignee gets inactive for 5+ days.
To keep our issue tracker organized, I will be closing this issue.
