### ISSUE TITLE
Adding proper links to social media icons

### ISSUE THREAD

**Issue by harikasayani** [sk66641/Random-Disco-Light-Simulator#256]
**Is your feature request related to a problem? Please describe.**
I observed that links for social media icons are not working.
I want to add proper links to social media icons

**Additional context**
I am GSSOC'24 Contributor.
Please assign me this task.
I want to work on this issue.

**Comment by sk66641** [comment]
@harikasayani 
Thank you for raising this issue. We've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
