### ISSUE TITLE
Enhancing feedback form

### ISSUE THREAD

**Issue by harikasayani** [sk66641/Random-Disco-Light-Simulator#257]
**Is your feature request related to a problem? Please describe.**
I observed that feedback form in web page is not looking good.

**Describe the solution you'd like**
I will add more CSS features to make it attractive and good.

**Additional context**
I am GSSOC'24 Contributor.
Please assign me this task.
I want to work on this issue.

**Comment by sk66641** [comment]
@harikasayani 
This issue has already been identified & is currently being addressed in #238 . You can follow the progress and participate in the discussion there.
