### ISSUE TITLE
Enhancing Feedback Page Usability and Functionality

### ISSUE THREAD

**Issue by thevijayshankersharma** [sk66641/Random-Disco-Light-Simulator#268]
**Is your feature request related to a problem? Please describe.**
Users currently face several usability issues with the feedback page that detract from their experience. For instance, there is no clear way to close the feedback form without submitting it, email inputs are not validated for correctness, star ratings lack interactivity, and the page height does not adjust properly, affecting its display.

**Describe the solution you'd like**
1. **Closing Button:** Introduce a prominent closing button on the feedback form to allow users to exit without submitting feedback unintentionally.
   
2. **Email Validation:** Implement validation for email inputs to ensure correctness and prevent submission of invalid email addresses.
   
3. **Star Ratings Update:** Enhance the functionality of star ratings to be interactive, allowing users to select their rating accurately.

4. **Adjust Page Height:** Ensure the feedback page adjusts its height dynamically to display all content correctly without unnecessary scrolling.

**Additional context**
![Feedback Page Screenshot](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/109781385/d4535a22-0ff6-459e-8b19-9c6e76cb5569)

**Comment by sk66641** [comment]
@thevijayshankersharma 
There is already an issue #264 for closing button #264. Btw the feedback form has been updated & it still has some other issues like non-adjusting page height.  Could you review the updated feedback form and update this issue?
