### ISSUE TITLE
Adding the upper limit on the number of colours you could select

### ISSUE THREAD

**Issue by anijit18** [sk66641/Random-Disco-Light-Simulator#269]
**Is your feature request related to a problem? Please describe.**
I noticed that you could enter enter number of colours you want. eg-99999999. 

**Describe the solution you'd like**
Therefore I intent to add some cap on the upper limit say - 1000.
And display the test error message to keep the number of colours below the required number.

**Additional context**

**Comment by anijit18** [comment]
@sk66641 Please assign this issue to me under GSSOC'24

**Comment by sk66641** [comment]
@anijit18 
Thank you for raising this issue. We've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. To keep our issue tracker organized, I will be closing this issue.
