### ISSUE TITLE
Add a Rate Us Option

### ISSUE THREAD

**Issue by sailaja-adapa** [sk66641/Random-Disco-Light-Simulator#271]
Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any. I will Change the page According to our Website below image is for Reference
Can you please assign me this issue under gssoc'24

![uuu](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/161804629/17c027fe-d347-4387-b7fe-90f1831c5328)

**Comment by sk66641** [comment]
@sailaja-adapa 
There is already a feedback form there in the menu bar (top left corner). If you have any additional issues, feel free to reach out. To keep our issue tracker organized, this issue will be closed.
