### ISSUE TITLE
Add icons to the items

### ISSUE THREAD

**Issue by sailaja-adapa** [sk66641/Random-Disco-Light-Simulator#272]
Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add icons to Items as you can see in the image

Can you please assign me this issue under gssoc'24

![tttt](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/161804629/a51e8c0d-55e8-433a-a6dd-9c68d2fc25a8)

**Comment by priti200** [comment]
Hey @sailaja-adapa,

I would like to work upon this issue as a GSSOC'24 contributor. Could you please assign me this issue.
thankyou!!!

**Comment by sk66641** [comment]
@priti200 
This issue has already been identified & is currently being addressed in #202. You can follow the progress and participate in the discussion there. You can comment there to get assigned if the assignee gets inactive for 7+ days.
To keep our issue tracker organized, I will be closing this issue.
