### ISSUE TITLE
Adding custom scrollbar to main page

### ISSUE THREAD

**Issue by ananya-dhiman** [sk66641/Random-Disco-Light-Simulator#283]
**Is your feature request related to a problem? Please describe.**
As the main page is lengthy enough to scroll but there is no manual way to do it.

**Describe the solution you'd like**
Adding a custom scroll for manual scrolling

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@sk66641
