### ISSUE TITLE
Main Page "Background Img" Issue After Changing the "Theme"

### ISSUE THREAD

**Issue by MastanSayyad** [sk66641/Random-Disco-Light-Simulator#285]
Hey @sk66641 

I have noticed the background image in Main Page Ui, it only shows when in Dark mode, after in light mode it disappears

- **Dark Mode:**

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101971980/650c9e3b-85fb-437a-a774-2bbcdb76e3e1)

- **Light Mode**

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101971980/05d7b4b8-7b49-4306-a51f-407dd9e2a53f)

I would like to take on this task could you please assign me this issue?

**Comment by aditya-bhaumik** [comment]
@MastanSayyad please complete this issue also with the other issue as its been 3 weeks since it was assigned

**Comment by MastanSayyad** [comment]
@aditya-bhaumik I completely forgot about this issue, You can unassign it from me.

**Comment by aditya-bhaumik** [comment]
@MastanSayyad closing this then as i think it is not needed
