### ISSUE TITLE
Enhancing the home page UI

### ISSUE THREAD

**Issue by vaishnavip27** [sk66641/Random-Disco-Light-Simulator#305]
The current UI of the homepage seems to be outdated, unappealing or not aligned with modern web standards which deter users from staying on the site. Important information might be buried or not highlighted properly making it hard for the users to find what they are looking for. I aim to address these problems, imrproving user satisfaction, engagement and overall site performance.
I want to update the visual design to be clean, appealing and aligned with the current website trends
The space between the two div's is not enough, creating a fuss and its difficult to actually read.

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143169451/1a102896-82e6-417f-870f-32ad391cf767)

**Comment by vaishnavip27** [comment]
@sk66641 please assign me this issue

**Comment by Shashank061103** [comment]
I would like to work on this Project. Please assign it to me.
