### ISSUE TITLE
Back button linking to homepage from all other pages

### ISSUE THREAD

**Issue by ananya-dhiman** [sk66641/Random-Disco-Light-Simulator#306]
**Is your feature request related to a problem? Please describe.**
No way to return back directly to the main page
**Describe the solution you'd like**
Adding a back button to all linked pages directing back to homepage.

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by sk66641** [comment]
@ananya-dhiman 
This issue is currently being addressed in #181. You can follow the progress and participate in the discussion there. You can comment there to get assigned if the assignee gets over a week.
