### ISSUE TITLE
Language button UI

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#325]
**Describe**
i would like to add minor changes to the language change button and improve its font size and style to match the vibe of the page and navbar

**To Reproduce**
1. Go to site
2. Click on navbar
3. See error

**Expected behavior**
-

**Screenshots**
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/144164397/7f526a78-0800-4ec2-89e0-52c8cdfacde4)

**Additional context**
Please assign this issue to me under gssoc'24

**Comment by sk66641** [comment]
It seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out.
