### ISSUE TITLE
Bug: pause functionality

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#326]
**Describe the bug**
during runtime of disco simulator, the pause button only pauses the screen not the background music

**To Reproduce**
1. Go to site
2. Start simulation
3. Pause simulation

**Expected behavior**
The music should pause as well as the screen. 

**Screenshots**

**Additional context**
Please assign this issue to me under gssoc'24

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@sk66641
