### ISSUE TITLE
 UI/UX Enhancements 

### ISSUE THREAD

**Issue by Muskan2025** [sk66641/Random-Disco-Light-Simulator#327]
I have identified a few UI enhancements that could significantly improve the overall look and feel of the application. Below are the specific changes I propose:

**Add the Logo to the Main Page:**

The main page can be made more visually appealing and branded by placing the project's logo prominently at the top. This will enhance brand recognition and give the page a more professional look.

**Change the Position of the Menu Bar:**

The menu bar's current position could be optimized for better accessibility and aesthetics. I propose moving it to a horizontal layout at the top of the page, which is a common design pattern that users find intuitive.

**Align the Text and Change the Font Style:**

Proper text alignment can greatly enhance readability. I suggest ensuring all text elements are left-aligned and consistently spaced.
Additionally, changing the font style to a more modern and clean typeface can make the content more attractive and easier to read. A font like "Roboto" or "Open Sans" could be a great choice.

main page :
![disco](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/104768631/c0568bb0-94fe-49a6-8e2f-2b1b1e60804b)

**Comment by sk66641** [comment]
This issue has already been identified & is currently being addressed in #305. You can follow the progress and participate in the discussion there.
