### ISSUE TITLE
Adding a FAQ Page

### ISSUE THREAD

**Issue by Ojas-Arora** [sk66641/Random-Disco-Light-Simulator#330]
**Is your feature request related to a problem? Please describe.**
@sk66641 I want to add a FAQ page to the website. Kindly assign this issue to me.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sk66641** [comment]
Thanks for raising this issue but i think it's not needed at the moment. If you have any additional issues, feel free to reach out.
