### ISSUE TITLE
Social Media icons does not lead to their respective pages

### ISSUE THREAD

**Issue by CoderGirl2844** [sk66641/Random-Disco-Light-Simulator#341]
On the main page the social media icons when selected show the main page again. 

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/155231566/1201a47d-c01c-4067-91c5-d3ec6972bb20

please assign this issue to me.

**Comment by sk66641** [comment]
@CoderGirl2844 
solved in PR #339
