### ISSUE TITLE
Make Scrollbar Thumb attractive

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#344]
**Is your feature request related to a problem? Please describe.**
This website scrollbar thumb is very unattractive 

**Describe the solution you'd like**
I want to add this type of linear gradient thumb color should white in upper side black shadow.

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/126322584/4bf572d7-6a48-45a8-b189-bc00dc5508fc)

**Like this but I will make color white and give shadow of black**

**Comment by zalabhavy** [comment]
@sk66641 Please assign me !

**Comment by yogirajbshinde21** [comment]
@sk66641 Is this issue fixed ?
Please assign this issue to me if not!
I would like to work on this issue immediately!

**Comment by zalabhavy** [comment]
@yogirajbshinde21 Please open another issue it is not correct way to comment in others issue and grab it !

**Comment by sk66641** [comment]
> @yogirajbshinde21 Please open another issue it is not correct way to comment in others issue and grab it !

@zalabhavy @yogirajbshinde21 
there is no such rule, anyone can ask in the comments for an issue to get assigned. You can checkout [guidelines](https://github.com/sk66641/Random-Disco-Light-Simulator#getting-started)
