### ISSUE TITLE
Redesign Feedback form

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#345]
**Is your feature request related to a problem? Please describe.**
I can see there is no placeholder in form also star starts from right side it is not good.

**Describe the solution you'd like**
I will Redesign this feedback form try to make it stylish.

**Comment by zalabhavy** [comment]
@sk66641 Please assign me !

**Comment by sk66641** [comment]
This issue  is currently being addressed in #302. You can follow the progress and participate in the discussion there.
