### ISSUE TITLE
adding confirm password in sign up page

### ISSUE THREAD

**Issue by me-nilakshi** [sk66641/Random-Disco-Light-Simulator#347]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to add **Confirm Password** field in sign up page where the user has to enter the same password as the **Password field**. If the **Confirm Password** is not equal to **Password,** it would show error in real time. This would prevent typos. 

**Record**
- [X]  I have read the Contributing Guidelines
- [X]  I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankita685** [comment]
@sk66641 i already solved this issue kindly accept my merge request

**Comment by sk66641** [comment]
@me-nilakshi 
Could you please give an update over this issue as it has been pending for over two weeks?

**Comment by me-nilakshi** [comment]
I'm working on it, will finish it by today
