### ISSUE TITLE
User navigation beyond the signin/signup page requires mandatory field completion.

### ISSUE THREAD

**Issue by me-nilakshi** [sk66641/Random-Disco-Light-Simulator#348]
**Describe the bug**
User can navigate to other pages on clicking Sign In or Signup button without filling any details. 

**Expected behavior**
Hi, I wanted the fields in login and signup page to be mandatory i.e., the user cannot move ahead without filling in the details of the page.

**Screenshots**
Here, as you can see I haven't filled in the details of sign in page. But on clicking Sign In, it navigates me to other pages. Same goes with register page.
![Capture](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/101091762/ca6965a1-9d80-4cb3-b6b8-a68883c4ee30)

**Record**
- [X]  I have read the Contributing Guidelines
- [X]  I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by me-nilakshi** [comment]
@sk66641 please assign this issue to me

**Comment by aditya-bhaumik** [comment]
@me-nilakshi hi its been a month since you were assigned this issue have you completed the task

**Comment by aditya-bhaumik** [comment]
@me-nilakshi i am closing this as there was no reply from you for a week
