### ISSUE TITLE
💡[Feature]: Add example for features

### ISSUE THREAD

**Issue by MuraliDharan7** [sk66641/Random-Disco-Light-Simulator#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add examples and pathways for the feature sub sections.

### Use Case

This helps users to quickly go through all the required steps.

### Add ScreenShots

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/130668745/4b43fd45-ae2b-4c37-8579-2e59ada1a7d8)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aman0474** [comment]
I would like to work on this issue i have understood the problem statement and will provide the optimal solution for it
