### ISSUE TITLE
Edit simulation button UI

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/144164397/2f13221a-8536-4ec9-827c-94e559b15f06)

### Expected behavior

I would like to improve the UI of this button to suit the page's navbar styles. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HarshadaGirase** [comment]
I would like to work on this issue. Kindly assign to me.
