### ISSUE TITLE
💡[Feature]:  adding new animation 

### ISSUE THREAD

**Issue by dnyandeepchute** [sk66641/Random-Disco-Light-Simulator#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding new animation to home page like snow fall

### Use Case

adding new animation to home page like snow fall

### Benefits

adding new animation to home page like snow fall

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@dnyandeepchute 
Thank you for raising this issue but it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out.
