### ISSUE TITLE
💡[Feature]: Implement Custom Captcha for Enhanced Login Security

### ISSUE THREAD

**Issue by aditya-bhaumik** [sk66641/Random-Disco-Light-Simulator#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement a custom captcha system on the login page that generates a random alphanumeric code displayed on a canvas element. Users must input the correct captcha code to proceed with login, enhancing security against automated attacks.

### Use Case

When a user attempts to log in, they are presented with a captcha code generated on a canvas. They must enter the displayed code in a text input field. If the input does not match the captcha, an error message appears below the login button, prompting the user to try again.

### Add ScreenShots

![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/92214013/072032ef-deaa-4525-af1f-078f3a4e79b2)

I will improve the design based on the design of the login page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@sk66641 please assign me this issue and the other 2

**Comment by aditya-bhaumik** [comment]
@sk66641 hi sorry i have been really busy this week will add all my pull requests today

**Comment by sk66641** [comment]
@aditya-bhaumik 
It's ok. Moreover, you can manage this repo if you want or if you have time as you have been contributing this from starting. I've invited you as a collaborator.

**Comment by aditya-bhaumik** [comment]
> @aditya-bhaumik It's ok. Moreover, you can manage this repo if you want or if you have time as you have been contributing this from starting. I've invited you as a collaborator.

@sk66641 
are we allowed to do that as a gssoc contributor ? I will start managing this repo after gssoc if it is not allowed 
i think only 10 days are left for the program

**Comment by sk66641** [comment]
@aditya-bhaumik 
read this 
![Screenshot from 2024-07-19 23-46-41](https://github.com/user-attachments/assets/5cd4a26f-41dc-44ec-818b-53c8e41a5de9)
although the mentors assigned to this repo are active

**Comment by aditya-bhaumik** [comment]
@sk66641 thank you for confirmation then i will manage this repo whenever i am free 
Thank you

**Comment by aditya-bhaumik** [comment]
@sk66641 i will review other contributor pull request but can you please review my pull request as i think it will be unfair to the other contributors if my merge my own pull requests

**Comment by sk66641** [comment]
@aditya-bhaumik 
ok

**Comment by sk66641** [comment]
> @sk66641 i will review other contributor pull request but can you please review my pull request when i add them as i think it will be unfair to the other contributors if I merge my own pull requests

yes

**Comment by sk66641** [comment]
@aditya-bhaumik 
are you on discord?

**Comment by aditya-bhaumik** [comment]
@sk66641 yes
