### ISSUE TITLE
🐞[Bug]:When Language selected the UI of page is improper

### ISSUE THREAD

**Issue by AfrozeSVU** [sk66641/Random-Disco-Light-Simulator#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @sk66641  ,
After selecting the language the UI page is not proper as it was in english. The font size getting increased. I would like to solve this under GSSOC'
![Screenshot 2024-07-05 171754](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/155154094/5546e0eb-8b73-421e-a262-127638a21b7f)
![Screenshot 2024-07-05 171837](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/155154094/a5de6d11-b032-4987-a487-454bedc99b45)
24

### Expected behavior

The UI of page after selecting the text would be similar as it was in english. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
Similar to #375
