### ISSUE TITLE
🐞[Bug]: Back button not working in About Page

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The back button present in the About page is not working showing a 404 Error page.

### Expected behavior

The back button should redirect to the main page.

### Add ScreenShots

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/7b6a3609-e6fc-4cb8-a83b-79ec2841d3ba

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prachi0701** [comment]
Hey, @AkshitGarg24 , Assign this issue to me!!

**Comment by sk66641** [comment]
It seems that someone has already fixed it in the previous PR. If you have any additional issues, feel free to reach out.
