### ISSUE TITLE
🐞[Bug]: Back button not working in Features Page

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The back button present in the Features page is not working showing a 404 Error page.

### Expected behavior

The back button should redirect to the main page.

### Add ScreenShots

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/153659573/6b0bf2dc-ff35-47a3-a002-3d655e032ff5

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prachi0701** [comment]
Hey, @AkshitGarg24 , Assign this issue to me!!

**Comment by sk66641** [comment]
It seems that someone has already fixed it in the previous PR. If you have any additional issues, feel free to reach out.
