### ISSUE TITLE
💡[Feature]: FAQ Enhancement with drop down feature.

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When user click on questions then dropdown open in that answer will be shown

### Use Case

Better feel

### Benefits

Better experience.

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@sk66641 Please assign me this task !

Thank You !

**Comment by sk66641** [comment]
It seems that someone has already fixed it in any previous PR. If you have any additional issues, feel free to reach out.
