### ISSUE TITLE
➕Improve FAQ Section with" Accordion Functionality" and "Improved Design"

### ISSUE THREAD

**Issue by aslams2020** [sk66641/Random-Disco-Light-Simulator#404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sk66641 ,

Currently, **all FAQ answers are displayed simultaneously,** which can be overwhelming for users. Additionally, **the design of the FAQ section can be enhanced** to **align better with the website's theme.**
Current FAQ Section - 
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/131389695/be5ccd22-202d-421f-8d25-485fd8cca486)

### What Will I Do -
1. Implement an accordion so that **when a user clicks on a question, the answer is displayed!**
2. All other answers should remain hidden until their respective questions are clicked.
3. **Apply a color theme** that aligns with the overall website design.
4. **Improve the main heading **to make it more attractive and consistent **with the website's styling.**
5. **Add more relevant FAQ questions** to provide comprehensive information to users.

### Use Case

.

### Benefits

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@sk66641 I'd like to work on this. Please assign me this issue

**Comment by sk66641** [comment]
It seems that someone has already fixed it in any previous PR. If you have any additional issues, feel free to reach out.
