### ISSUE TITLE
🐞[Bug]: Removing background Image in FAQ 

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The background image present in the FAQ page should be removed and a proper space should also be given at the bottom of the container.

### Expected behavior

I have mentioned

### Add ScreenShots
First Image
![1](https://github.com/user-attachments/assets/b781bda8-5927-4d88-85ec-7d2998f9d99d)

Second Image
![2](https://github.com/user-attachments/assets/a8056f53-7c4d-4fa9-81dd-88e11e8763f4)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@AkshitGarg24 
I think the page looks better with the image.
