### ISSUE TITLE
💡[Feature]: Changing UI of certsin buttons on the home page.

### ISSUE THREAD

**Issue by taneeshaa15** [sk66641/Random-Disco-Light-Simulator#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will change the UI of certain buttons.

### Use Case

The homepage will look more good and attractive.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@sk66641 Please assign me this issue under gssoc'24.

**Comment by sk66641** [comment]
@taneeshaa15 
this issue looks similar to #405
