### ISSUE TITLE
💡[Feature]:  Submit and Reset button not clearly visible in the main page. (Dark Mode)

### ISSUE THREAD

**Issue by anijit18** [sk66641/Random-Disco-Light-Simulator#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Choosing the right text colour and background colour for the specified button will make it look more appealing to the users.

### Use Case

Currently the specified buttons are not clearly visible and strains the eye.
Improving the colour enhances the user experience.

### Add ScreenShots

![Screenshot 2024-07-13 122820](https://github.com/user-attachments/assets/8fb38af2-4db8-4665-995b-4ebe959be2fe)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@anijit18 
this issue looks similar to #405
