### ISSUE TITLE
💡[Feature]: Option of Light-Mode in Privacy Policy

### ISSUE THREAD

**Issue by VijaySamant4368** [sk66641/Random-Disco-Light-Simulator#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There should be a toggle button(the same as the one in the home page) that can be used to toggle between dark-mode and light-mode.

### Use Case

Adding of mode preference on this page will be better for User-Experience

### Priority

Medium

### Record

- [x] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshulagr5** [comment]
@sk66641 I would like to work on this issue. Kindly assign it to me.
