### ISSUE TITLE
🐞[Bug]: Terms/Privacy page in small screen margins not proper also back arrow not works and both are not align proper.

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**1 For both page**
![image](https://github.com/user-attachments/assets/d72f3a99-45ae-4735-91b9-cec9c8e4c2cd)

**2 For both page**
![image](https://github.com/user-attachments/assets/01f5ee97-1122-4077-b045-47d09b5b2d4b)

**3 For index.html page**
![image](https://github.com/user-attachments/assets/cf49b9b0-bcb1-4175-99b4-b70ca4765c1a)

### Expected behavior

NA

### Add ScreenShots

NA

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@sk66641 Please assign me this task thank You !

**Comment by sk66641** [comment]
@zalabhavy 
i think this has been fixed in any previous pr, can you check it once?

**Comment by zalabhavy** [comment]
@sk66641 Yes this is fix i am close this ...
