### ISSUE TITLE
🐞[Bug]: terms and conditions and privacy policy is not visible in light mode 

### ISSUE THREAD

**Issue by ANKeshri** [sk66641/Random-Disco-Light-Simulator#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

terms and conditions and privacy policy is not visible in light mode 

### Expected behavior

it should be visible in both mode 

### Add ScreenShots

https://github.com/user-attachments/assets/5592c39f-0066-4f13-90d4-e67b04b29908

![Screenshot 2024-07-14 150109](https://github.com/user-attachments/assets/11f14938-de31-42a0-8402-909c93d0edcb)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@ANKeshri closing this as it is already resolved in #433
