### ISSUE TITLE
🐞[Bug]: Making UI of FAQ page similar to other pages

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The FAQ page should be made similar to other pages.

1. Proper spacing should be given between the container and the footer.
2. The background color of footer should be same as that of the background color of body, as implemented in other pages. 

### Expected behavior

Mentioned Above.

### Add ScreenShots

![Footer](https://github.com/user-attachments/assets/35145ab9-4098-4a9d-9db5-b2c85d369c76)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepak2047** [comment]
i would like to work on this project.please assign to me.
