### ISSUE TITLE
📝[Docs]:  GitHub Desktop Contribution Instructions

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [sk66641/Random-Disco-Light-Simulator#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Description ✍️
I am interested in contributing to the project by adding detailed instructions on how to contribute using GitHub Desktop.

### Suggested Change

I believe that by providing clear and comprehensive guidance, we can encourage more contributors to participate in the project, especially those who prefer using GitHub Desktop for their contributions.

Could you please assign me the issue related to adding GitHub Desktop contribution instructions under gssoc24? I am excited about the opportunity to contribute to the project and help streamline the contribution process for others.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@iamkanhaiyakumar sure go ahead

**Comment by iamkanhaiyakumar** [comment]
@aditya-bhaumik Sir for this PR i did not any point Why Can you Oepn the issue gain i will make again pr request

**Comment by iamkanhaiyakumar** [comment]
@sk66641 @aditya-bhaumik 
Can you open the pr issue again and cancle merged request 
I talked to PM that said if you again raised PR and merged it you will get points

**Comment by aditya-bhaumik** [comment]
@iamkanhaiyakumar you already got level 2 for this why do want to open this pr again

**Comment by aditya-bhaumik** [comment]
@iamkanhaiyakumar i have changed the label in your pr now it should be equivalent to the 2 issue points

**Comment by iamkanhaiyakumar** [comment]
@aditya-bhaumik But in leadboard show PR #485 only because both isuue are in one this cause i did not get any point
You open the issue i merged in few second

**Comment by aditya-bhaumik** [comment]
@iamkanhaiyakumar i have changed the label now it will update in 12 hours

**Comment by aditya-bhaumik** [comment]
2 issues is 20 points you had done it in one pull request only  i did not see that so gave you level 1 just updated it to level 2 which is 25 points

**Comment by iamkanhaiyakumar** [comment]
@aditya-bhaumik So let's wait and see what happens tomorrow, the point will be added to the leadboard.
