### ISSUE TITLE
📝[Docs]: Adding Installation and Setup Guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [sk66641/Random-Disco-Light-Simulator#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully.

### Suggested Change

I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

I've done a readme file for another project, you can check my profile, i always give my best.

Can you assign me this task?

Thank u @sk66641 

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@iamkanhaiyakumar 
But there is already a [Learn.md](https://github.com/sk66641/Random-Disco-Light-Simulator/blob/main/Learn.md) file for this linked in readme file [here](https://github.com/sk66641/Random-Disco-Light-Simulator?tab=readme-ov-file#getting-started)

**Comment by iamkanhaiyakumar** [comment]
@sk66641 But  here is not full and complete guide . You see my work [Here](https://github.com/singodiyashubham87/Draw-it-out)
