### ISSUE TITLE
🐞[Bug]:  Home web page isn't responsive for devices of width between 400 & 300 px

### ISSUE THREAD

**Issue by sk66641** [sk66641/Random-Disco-Light-Simulator#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Home web page isn't responsive for devices of width between 400 & 300 px

### Expected behavior

since most of the smart phones lie in this range, it should be responsive

### Add ScreenShots

![Screenshot from 2024-07-20 01-13-10](https://github.com/user-attachments/assets/e5bdeeb9-9c82-4f99-8009-b4a811936098)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by sk66641** [comment]
Issues are assigned on the basis of “first come, first served.”

**Comment by ayushkamboj18** [comment]
I can do this, please assign to me
