### ISSUE TITLE
🐞[Bug]: Improve light mode in privacy policy and terms and conditions

### ISSUE THREAD

**Issue by aditya-bhaumik** [sk66641/Random-Disco-Light-Simulator#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is a problem with the new light theme 

1. the content is not visible as it is white 
2. the container become bigger in light theme but it should stay the same as how it is in the dark theme

### Expected behavior

This is first come first serve whoever would like to work on this please comment below

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d082c150-abfe-487d-aedb-1ccb0ffb3883)

![image](https://github.com/user-attachments/assets/59997ba2-bf25-47f8-91f6-737174f6576f)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Parth20GitHub** [comment]
Please assign this task to me

**Comment by aditya-bhaumik** [comment]
@Parth20GitHub have you completed the task

**Comment by aditya-bhaumik** [comment]
@Parth20GitHub as i did not get a reply i am unassigning this

**Comment by aditya-bhaumik** [comment]
@sk66641 can you please assign me this issue as gssoc is coming to an end in 6 days i would also like to contribute for some time

**Comment by sk66641** [comment]
@aditya-bhaumik sure

**Comment by aditya-bhaumik** [comment]
@sk66641 i think someone has already fix this so i am closing it
