### ISSUE TITLE
🐞[Bug]: TextBoxes are not accepting the text

### ISSUE THREAD

**Issue by gollaanusha249** [sk66641/Random-Disco-Light-Simulator#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The text boxes for 'Number of Colors' and 'Time Travel' are not accepting input. When we try to enter text, it isn't being accepted.

### Expected behavior

When we enter any text, the text should appear

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@gollaanusha249 it is working you need to enter a number in them not a text
