### ISSUE TITLE
💡[Feature]:  Better Mode-Toggler

### ISSUE THREAD

**Issue by VijaySamant4368** [sk66641/Random-Disco-Light-Simulator#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Improving the Bland Mode Toggler to a new, better one

### Use Case

All the use cases of the normal mode toggler

### Benefits

It will improve the UI

### Add ScreenShots

Current Toggler:
![image](https://github.com/user-attachments/assets/ae9d0041-36b4-47b9-bea3-4b6abcae43cf)

New Toggler:
![image](https://github.com/user-attachments/assets/d78ffaad-de11-4615-8c39-9e9d7f85e616)
![image](https://github.com/user-attachments/assets/e7e89949-2e26-47b7-97aa-aad0b86b6a5b)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik please check this out.

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 go ahead

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik please checkout the pr
