### ISSUE TITLE
🐞[Bug]: Home page is not responsive on mobile screen

### ISSUE THREAD

**Issue by K-kiran77** [sk66641/Random-Disco-Light-Simulator#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When user accessing the website on mobile the home page is overflowing screen and hiding

### Expected behavior

When user accessing the website on mobile screen the home screen contents are made responsive to mobile screen

### Add ScreenShots

![Screenshot_2024-07-22-06-12-07-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5348d1c5-813c-4dff-9408-4ed7095b570f)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@K-kiran77 
it seems like it has been fixed in any previous pr
