### ISSUE TITLE
Creating LOGO for the website

### ISSUE THREAD

**Issue by aartijangra** [sk66641/Random-Disco-Light-Simulator#49]
### Issue Title: Create a Logo for the Random Disco Lights Simulator Website

**Description:**

We need a visually appealing and creative logo for the Random Disco Lights Simulator website. The logo will be used on the website's homepage, favicon, social media profiles, and any promotional materials. The design should reflect the fun, vibrant, and dynamic nature of the project.

**Requirements:**

1. **Concept and Theme:**
   - The logo captures the essence of "disco" with a modern twist.
   - It incorporates elements that represent lights, randomness, and simulation.
   - The design is colorful and energetic, resonating with the project's lively theme.

2. **Design Specifications:**
   - **Sizes:** The logo is scalable and available in different sizes for various uses (e.g., website header, favicon, social media).
   - **Typography:** The font of the text included is legible and complements the overall design.

3. **Creativity and Originality:**
   - The design is original and not infringe on any existing trademarks or copyrights.

I am excited about the possibility of contributing to this project and enhancing its visual appeal. Please let me know if you approve of this idea or if there are any specific requirements or preferences you have for the logo design. @sk66641 

Looking forward to your response.
Thank you!

**Comment by Stylyan** [comment]
can you please assign me this issue. I would like to work on it.
