### ISSUE TITLE
💡[Feature]:  Feedback Addition with emoji review section

### ISSUE THREAD

**Issue by Damini2004** [sk66641/Random-Disco-Light-Simulator#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Feedback Addition with emoji review section

### Use Case

Feedback Addition with emoji review section

### Benefits

Feedback Addition with emoji review section

### Add ScreenShots

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrDAoBFf9sVLD44Mb13cgodpi_HVZkqG1zTQ&s

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@Damini2004 
i think you have already been assigned this issue in #424
