### ISSUE TITLE
Enhance Web Page and Add Background

### ISSUE THREAD

**Issue by techinaina** [sk66641/Random-Disco-Light-Simulator#5]
Hey @sk66641 
The current state of the web page is quite plain and lacks visual appeal, which can affect user engagement and overall user experience. To address this, the enhancement of the web page by adding a background is proposed. Enhancing the web page by adding a background will significantly improve its visual appeal and user experience. By carefully selecting a suitable background and implementing it with responsive design in mind, the web page will become more engaging and professional. I would like to add background effect and enhance web page.

Please assign me this under Gssoc'24

**Comment by techinaina** [comment]
please assign me this issue i really want to work on this

**Comment by sk66641** [comment]
this issue has already been raised and assigned in issue #7. So, will have to wait:)
