### ISSUE TITLE
💡[Feature]: Make select language attractive

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/a1552944-ae5c-4b89-80fe-0a9582a184a7)

I will style this and make it attractive.

### Use Case

Better UI

### Benefits

NA

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@sk66641 Please assign me this task !

Thank You !

**Comment by aditya-bhaumik** [comment]
@zalabhavy sure go ahead
