### ISSUE TITLE
🐞[Bug]: Password Toggle Functionality Fails When Elements Are Missing

### ISSUE THREAD

**Issue by Swapnilden** [sk66641/Random-Disco-Light-Simulator#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the DOM elements for password toggling (e.g., password input fields or toggle buttons) are missing, the script throws an error and prevents further execution. An error is thrown in the console, preventing the execution of subsequent scripts or interactions on the page.

### Expected behavior

The script should gracefully handle the absence of these elements without throwing errors, allowing the rest of the page functionality to continue working as expected.

### Steps to Reproduce
1. Navigate to the page where the password toggle script is included.

2. Remove or comment out the HTML elements for the password input fields or toggle buttons.

3. Load the page and check the console for errors.

### Add ScreenShots

N/A

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@Swapnilden 
are you talking about that login page?

**Comment by Swapnilden** [comment]
@sk66641 Yes
