### ISSUE TITLE
💡[Feature]: Add light/dark mode toggle feature on all pages

### ISSUE THREAD

**Issue by meetarora10** [sk66641/Random-Disco-Light-Simulator#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add light/dark mode toggle feature on About Us page .

### Use Case

This will make the website look more attractive if features for two modes are present .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by raju2109** [comment]
Please assgn me this issue under GSSoC '24 i will work on it.

**Comment by aditya-bhaumik** [comment]
@meetarora10 please add it in all the other pages as well which does not contain i think the privacy and terms and condition already has it 
add it in other pages i will update to 3 based on your pull request

**Comment by aditya-bhaumik** [comment]
@raju2109 please create a another issue its first come first serve you can create your own issue i will assign it to you

**Comment by meetarora10** [comment]
@aditya-bhaumik ok I will add in all the pages .
