### ISSUE TITLE
🐞[Bug]: Chat with us button

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Chat with us button should not show when the loader is in motion 

### Expected behavior

The chat with us button should load with the rest of the main display elements

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 this issue has been solved i think i am closing this issue
