### ISSUE TITLE
🐞[Bug]: Loader: once per session

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The loader appears even when the user navigates from about us page to home page

### Expected behavior

Loading animation should appear only once per session

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
it is happening for all pages so fix it for the other pages also when you are fixing this bug
