### ISSUE TITLE
🐞[Bug]: Different theme slider 

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The slider for the theme has different styles on the main page and on the other side pages

### Expected behavior

The site should be uniform and have same style of theme toggle on each page 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e9ee6f60-2d23-4762-a9ad-14d7794067e3)
![image](https://github.com/user-attachments/assets/b7cef4d0-cc71-4599-bb30-79ad5bd62721)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Jasleen1210** [comment]
Hi @aditya-bhaumik which slider is supposed to be on all pages [the top one or bottom one in the issue images]?

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 top
