### ISSUE TITLE
💡[Feature]: Light mode for FAQ page

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Styles for faq page for light mode seem to be absent. Id like to add suitable light mode styling to the page

### Use Case

-

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 already being worked on in #508
