### ISSUE TITLE
💡[Feature]: "Preset saved successfully" modal

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Instead of the current alert for "saved successfully" and loaded successfully for presets, id like to add timed notifications 

### Use Case

-

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 @sk66641 isnt this same as #517 it can be done in that issue only right
