### ISSUE TITLE
Removing unwanted code

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed alot of code that is no longer needed which is commented out rather than being deleted

### Expected behavior

It does not affect the page however it does take up unnecessary space and lines in the pages, may i delete such lines?

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9075bfe5-14e0-4095-a659-a679f7e9d473)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@Jasleen1210 
ok fine but remove it carefully
