### ISSUE TITLE
🐞[Bug]: Back to top button not matching the theme

### ISSUE THREAD

**Issue by VijaySamant4368** [sk66641/Random-Disco-Light-Simulator#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The back to top button looks very out of place:

### Expected behavior

It should match with the theme of the website.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6ec19366-bd19-4201-9398-b20764dbc3e4)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@sk66641 please kindly have a look.

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 sure go ahead

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 i have reopened this issue please fix the problem and create another pull request
