### ISSUE TITLE
🐞[Bug]: Lots of problems in many web-pages

### ISSUE THREAD

**Issue by VijaySamant4368** [sk66641/Random-Disco-Light-Simulator#526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the following webpages:
- Features page
- Our Contributors
- Privacy Policy
- Terms and Conditions
- About
There is a problem that the width of the content is changing a lot when toggling between modes:

- Our Contributors
- Privacy Policy
- Terms and Conditions
- About
There is a problem that when viewed in mobile view, there is a lot of unnecessary gap above the main heading

### Expected behavior

These should be resolved to make it better responsive.

### Add ScreenShots

For the different mode problems:
![image](https://github.com/user-attachments/assets/f56ecdb6-9fa2-4bfc-8c86-c25f349fa32e)
![image](https://github.com/user-attachments/assets/5179e320-06c8-4e04-b773-23462f47121b)

For the mobile view problem:
![image](https://github.com/user-attachments/assets/2ca2865a-9df1-4122-8833-97e4ec637246) 

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@sk66641 please kindly have a look.

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 sure go ahead

**Comment by SrishtiSrishti01** [comment]
@aditya-bhaumik These seems to be a lot of bugs. Please assign this to me as well.
