### ISSUE TITLE
🐞[Bug]: Theme toggle error

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the about us page, the toggle does not change themes  and is not aligned properly
![image](https://github.com/user-attachments/assets/c95ed241-fecb-4cd5-aef7-eac6ae24db0a)
Please allow me to fix all pages that have this problem

### Expected behavior

-

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 fix it for all pages
