### ISSUE TITLE
➕Feature: Adding Diagonal-Transitional Effect to "Each Contributors Card"

### ISSUE THREAD

**Issue by aslams2020** [sk66641/Random-Disco-Light-Simulator#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sk66641 and @aditya-bhaumik 

I want to suggest a new feature for "Contributors" Page.

I Want **to add a "Diagonal-Transitional" Effect Styling to each card** of the Contributors page. 
Which means On hovering on Every card, The card will display a Transitional Effect

**For ex.  Like this -(I will follow the StarConnect website theme)** 

https://github.com/user-attachments/assets/b70c3c22-fc3f-4397-854f-53a413bf4d60

**Current Contributor Cards -** 

https://github.com/user-attachments/assets/e303b380-2e55-486b-9695-9c80e9381f37

As you can see, currently the hovering effects are lagging and have no smooth hover effect.

Please Assign me this issue.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@aslams2020 i think someone is already working on that #532 

If the changes are different i will open this comment again for now i am closing it as completed

**Comment by aslams2020** [comment]
Ohk @aditya-bhaumik , i understand

**Comment by aslams2020** [comment]
> @aslams2020 i think someone is already working on that #532
> 
> If the changes are different i will open this comment again for now i am closing it as completed

@aditya-bhaumik Could you please assign me now ? as the changes are completely different from my proposed changes

**Comment by aslams2020** [comment]
@aditya-bhaumik Could you please assign me this work?
