### ISSUE TITLE
🐞[Bug]: A black bar on faq page

### ISSUE THREAD

**Issue by Jasleen1210** [sk66641/Random-Disco-Light-Simulator#539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/37e21552-4bf8-40ab-a7ea-442903507603)
was this supposed to contain something that has been deleted?

### Expected behavior

-

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 you can remove it

**Comment by Jasleen1210** [comment]
@aditya-bhaumik I looked into it, its on all the pages it has the class name of the navbar, i think removing it might undo the work of whoever wished to add navbar, is an issue for the same still open or what?
Let me know if i can modify this issue and and fix the navbar on pages

**Comment by aditya-bhaumik** [comment]
@Jasleen1210 i think someone fixed it as other pages i cant see this issue

**Comment by Jasleen1210** [comment]
the navheader code is added on all pages, on faq page it shows a black bar, the rest pages it shows neither the actual icon nor the black bar
do i just remove the code snippet on faq page so it doesnt show? or do i remove from all as it is faulty code? or do i fix it?

**Comment by sk66641** [comment]
@Jasleen1210 
you can remove it from all if it's faulty code
