### ISSUE TITLE
💡[Feature]:  Add a Scroll "Progress Indicator Bar" 

### ISSUE THREAD

**Issue by Tejashri-Taral** [sk66641/Random-Disco-Light-Simulator#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sk66641 and @aditya-bhaumik  ,
I want to add a "Scroll Down Progress Bar" to the all pages present in website like privacy policy,terms and condition ,our contributors and all.

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.

### Use Case

The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

![348317613-b1d6b10c-18af-4cdf-a901-a8f6d91c6815](https://github.com/user-attachments/assets/6ecb21d7-c685-40ba-98b4-554b68b46c25)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@Tejashri-Taral i dont think it will look nice in this website
