### ISSUE TITLE
➕ Add Dynamic "Last Updated" Functionality to All Legal Pages ! 

### ISSUE THREAD

**Issue by aslams2020** [sk66641/Random-Disco-Light-Simulator#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @sk66641 @aditya-bhaumik 

I want to add a **"Last Updated: " functionality** to the legal pages of the website,
 specifically the **Privacy Policy, Terms and Conditions**. 
This functionality **will be dynamically adjustable to update monthly and yearly.**

Please Refer to the attached image **for an example** of how the functionality should look

![image](https://github.com/user-attachments/assets/82d095af-1044-463a-83c0-f98aeeb8e4e3)

## **Currently, The Legal Pages Do not have these Updates, Which makes user feel Outdated.**
![image](https://github.com/user-attachments/assets/53260e91-1404-4b4a-8833-1cd953fde51f)

## Use Case 
**Monthly Update for Privacy and Terms Pages:**
At the start of a new month, the system automatically updates the date on the Privacy page to reflect the current month and year (e.g., "Last updated: August 2024").

I want to work on this, please assign me.
thankyou 

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@aslams2020 sure go ahead
