### ISSUE TITLE
Warning sign for light sensitivity 

### ISSUE THREAD

**Issue by siya25097** [sk66641/Random-Disco-Light-Simulator#56]
Hey @sk66641, i would like to add warning sign for people with light sensitivity like 
![Screenshot_20240529-181808](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/143542717/68d05a9d-51f4-47c9-a89a-05fbe54251ff)

Please assign this to me under gssoc 2024
Thankyou

**Comment by sk66641** [comment]
@siya25097 ok, but change the look as [this](https://private-user-images.githubusercontent.com/143542717/334804752-68d05a9d-51f4-47c9-a89a-05fbe54251ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMDUzNTQsIm5iZiI6MTcxNzAwNTA1NCwicGF0aCI6Ii8xNDM1NDI3MTcvMzM0ODA0NzUyLTY4ZDA1YTlkLTUxZjQtNDdjOS1hODlhLTA1ZmJlNTQyNTFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQxNzUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTA1ZWU2ZDA4MTA1ZjM1YTVkYzk4ZWRkZTI5MTgxNDJkYWZmODMwMGU2NjU3ZDlkZjQzYTc2YTBjYzk3NmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kvxZ9ADn6sdGxqSQyQi9-gRM-x6Nrlp1-xmT1FlEm8U) matches to moodlight.org warning!
