### ISSUE TITLE
💡[Feature]: UI Improvement buttons

### ISSUE THREAD

**Issue by vivekvardhan2810** [sk66641/Random-Disco-Light-Simulator#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![Screenshot 2024-08-05 220400](https://github.com/user-attachments/assets/e90b5a15-676c-4448-b448-ad7963a7b6be)

### Use Case

I want to Improve the UI

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by crazyshrut** [comment]
hey @vivekvardhan2810 , I am a gssoc contributor.
Can you assign this to me?

**Comment by vivekvardhan2810** [comment]
@crazyshrut sorry already working on this.
I am creating my Pull request tonight.
