### ISSUE TITLE
🐞[Bug]: In feedback form if all inputs filled then show thank you message.

### ISSUE THREAD

**Issue by zalabhavy** [sk66641/Random-Disco-Light-Simulator#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If try after fill name and email then forms submitted and show message i want to check all options are filled or not when all inputs not filled show message that please fill all the details.

### Expected behavior

NA

### Add ScreenShots

NA

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@aditya-bhaumik Please assign me this task !

Thank You !

**Comment by aditya-bhaumik** [comment]
![image](https://github.com/user-attachments/assets/6cc2b3fc-6c38-4a80-8b91-7554d74c3d18)


Already there
