### ISSUE TITLE
🐞[Bug]: Non visible date in "Privacy Policy" and "Terms and Conditions" page.

### ISSUE THREAD

**Issue by VijaySamant4368** [sk66641/Random-Disco-Light-Simulator#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a very small bug in the two pages. When in light mode, the font color of the date is white, and is therefore blending with the background, and hence invisible.

### Expected behavior

The font-color should be black.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/e0f466aa-4293-45f9-82eb-66c4a2ee7643)
![image](https://github.com/user-attachments/assets/937772b4-0e9d-4aac-9b9b-ece2f6048342)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 sure go ahead

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 tommorrow is the last day to contribute so try to complete by today night so that you can work on more issues

**Comment by VijaySamant4368** [comment]
@aditya-bhaumik can we complete even after tomorrow, not for points but just because we want to?

**Comment by aditya-bhaumik** [comment]
@VijaySamant4368 you can work as much you like but for gssoc tommorrow is last day 

Rest its in the project admin's hand if he wants to continue or take a break from reviewing pull requests
