### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sk66641** [sk66641/Random-Disco-Light-Simulator#63]
update contribution section in [README.md](https://github.com/sk66641/Random-Disco-Light-Simulator/blob/main/README.md)

**Comment by AkshatBujethiya** [comment]
I would like to work on this issue. Please assign this issue to me. Also, can you elaborate what do I need to change in the contribution section.

**Comment by sk66641** [comment]
@AkshatBujethiya 
there was a delay in updating contributor information and actually it's 
due toGitHub’s API has rate limits to prevent abuse. If Contrib.rocks exceeds these limits, it may need to wait before making additional requests, causing delays in updating contributor information.
I'm closing this issue! Thanks for commenting!
