### ISSUE TITLE
Nomination

### ISSUE THREAD

**Issue by sk66641** [sk66641/Random-Disco-Light-Simulator#643]
[Click here if you want to nominate PA](https://substack.com/redirect/01588d98-d859-4634-bcea-fd3fa281ae40?j=eyJ1IjoiM3VneWRwIn0.gDGtDSqVgdccqM7ColtpOdjwQYM7AA2fUmXX2lKwCyM)
[Click here if you want to nominate Mentor](https://substack.com/redirect/c5201aff-bd2a-439d-ba0f-8c3ffded1e71?j=eyJ1IjoiM3VneWRwIn0.gDGtDSqVgdccqM7ColtpOdjwQYM7AA2fUmXX2lKwCyM)
@aditya-bhaumik @Jasleen1210 @MastanSayyad @RadhikaMalpani1702 @aslams2020 @ananya-dhiman @AkshitGarg24 @VijaySamant4368 @Ojas-Arora @vivekvardhan2810 @siya25097 @SuhainaFathimaM @Trevisx07 @zalabhavy @meetarora10 @thevijayshankersharma @AbheetHacker4278 @Asymtode712 @sujal-98 @Santhosh-Siddhardha @taneeshaa15 @kritzxd8 @muskan42 @Jagpreet153 @BHS-Harish @AkhilaSunesh @MuraliDharan7 @TonyStark-47 @rashiranjan22 @Tejashri-Taral @ishap11 @DiwareNamrata23 @Riddhi162 @yeolesanskruti @shreya-paul-17 @kashnx @solanki505 @sidharth2829 @sabhansali @aartijangra @ayushkamboj18 @nagalakshmi08 @ANKeshri @me-nilakshi @partha120804 @SrinivasDevolper @agarwalhimanshugaya @gangwarsomya @HJ2207 @animex007

**Comment by sk66641** [comment]
[Click here if you want to nominate](https://substack.com/redirect/01588d98-d859-4634-bcea-fd3fa281ae40?j=eyJ1IjoiM3VneWRwIn0.gDGtDSqVgdccqM7ColtpOdjwQYM7AA2fUmXX2lKwCyM)
@Shashanktriathi1703 @jayanththalla @Vibha17 @piyushsahujtp @Ramben0909 @bheemajayashreee @dishathakurata @ankiiitagupta @PradnyaGaitonde @Chandu6702 @swetha5157 @Khushipawar37 @Ketanop321 @debangi29 @sweta-singh28 @Tapesh-1308 @vishal02527 @Shashank061103 @anijit18 @ananyag309 @shreyasmunge @parth8672 @Swapnilden @sharmi4590 @satya-sl @sreevidya-16

**Comment by aditya-bhaumik** [comment]
@sk66641 nominated 

can anyone nominate me as the best mentor :sweat_smile:
