### ISSUE TITLE
💡[Feature]: improve heading speed

### ISSUE THREAD

**Issue by shivamyadavrgipt** [sk66641/Random-Disco-Light-Simulator#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

slow down heading speed

### Use Case

it'll increase smoothness of changing text

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sk66641** [comment]
@shivamyadavrgipt 
by how much you want to change it?
it would be better if you keep it at 75...

**Comment by shivamyadavrgipt** [comment]
Ok, i'll do it
