### ISSUE TITLE
Social Media Icons Not Navigating to Respective Pages

### ISSUE THREAD

**Issue by Samridhi002** [sk66641/Random-Disco-Light-Simulator#67]
### Description:
When I click on the social media icons (Facebook, Twitter, etc.) at the bottom of the Random Disco Light Simulator page, they do not navigate to their respective social media pages. And moreover the old logo of Twitter should be replaced by new one.

### Steps to Reproduce:

1. Open the Random Disco Light Simulator page.
2. Scroll down to the bottom in the footer section where the social media icons are located.
3. Click on any of the social media icons (e.g., Facebook, Twitter).

### Expected Behavior:
Clicking on a social media icon should navigate to the corresponding social media page.

### Attachment:
![Screenshot (23)](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/169380578/d309e4e9-b05f-4e4c-a92f-85c96ff707dc)

I can solve this issue once you assign it under GSSoC'24. And it would be really helpful if you provide me with your respective social media handles. Thank You!

**Comment by sk66641** [comment]
@Samridhi002 Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out.
