### ISSUE TITLE
Improper Footer Implementation

### ISSUE THREAD

**Issue by AkshitGarg24** [sk66641/Random-Disco-Light-Simulator#73]
The footer currently lacks clarity in the visibility of social media links and does not adhere to proper implementation standards. To improve this, the footer should be redesigned to include the website's name prominently, along with copyright information. Additionally, the social media links should be made more visible and accessible.

Being a GSSoC'24 contributor, I want to work on this issue.

**Comment by diyaaa19** [comment]
@sk66641 please assign this issue to me under gssoc'24, I'll shift the header which is not visible to the top, so it's easily visible and accesible. Thanks
