### ISSUE TITLE
comment option

### ISSUE THREAD

**Issue by Varsani2520** [sk66641/Random-Disco-Light-Simulator#84]
@sk66641 ,
we will add comment section ,
where user can add the her opinion about disco light 

for me it's such a wonder!

**Comment by shivathmikavemula** [comment]
please assign me the task @sk66641

**Comment by Aryan-joh** [comment]
please assign this project to me @sk66641 i will add the comment section

**Comment by Varsani2520** [comment]
thanks @sk66641

**Comment by shendgeshraddha** [comment]
Please add this task to me I'll add comment section
