### ISSUE TITLE
[Feature] : Add Mute Button to Simulation Page

### ISSUE THREAD

**Issue by aditya-bhaumik** [sk66641/Random-Disco-Light-Simulator#91]
### Description:
This feature involves adding a mute button to the simulation page. The mute button will allow users to mute and unmute the background music during the simulation. Initially hidden, the button will become visible when the user starts the simulation. This enhancement will provide users with greater control over their simulation experience by allowing them to easily toggle the background music on and off.

### Details:
Introduce a mute button element in the HTML code.
Initially, the mute button will be hidden using inline CSS styling (style="display:none;"). The button will be displayed dynamically using JavaScript when the user clicks the submit button to start the simulation.
Implement functionality to mute and unmute the background music when the button is clicked. This will ensure users can control the audio without needing to reload the page.
Ensure the mute button will work for all songs in the dropdown, allowing users to mute and unmute any selected background track seamlessly.
The mute button provides an additional layer of user control, enhancing the overall user experience by allowing them to manage the audio according to their preferences.
Ensure the mute button integrates seamlessly with the existing music selection dropdown and other simulation features, maintaining a clean and intuitive user interface.

### Implementation Steps:
Add a mute button element in the HTML.
Use CSS to hide the button initially.
Utilize JavaScript to make the button visible when the simulation starts.
Implement JavaScript functions to handle muting and unmuting of the background music.
Ensure the mute button's functionality works smoothly with the existing music dropdown.
Verify the mute button works for all music tracks available in the dropdown, providing consistent audio control across all selections.

**Comment by thevijayshankersharma** [comment]
@sk66641 Assign this task to me.

**Comment by sk66641** [comment]
@thevijayshankersharma 
Issues are assigned on the basis of “first come, first served.” Others get a chance if the issue gets stale and the assignee is inactive for 5+ days.

**Comment by sk66641** [comment]
@aditya-bhaumik 
Would you like to work on this issue as it has been pending for over two weeks?

**Comment by thevijayshankersharma** [comment]
@sk66641 if he is not then i will like to do it.

**Comment by aditya-bhaumik** [comment]
@sk66641 Adding this feature has been a little challenging as before it was working but when the other feature was added the youtube url one then the mute button started causing problem and because i have my exams now i cant give proper time. Thats why i have been making simpler for the last couple of days and adding them  

I was about to do it after the exams but you can assign to @thevijayshankersharma as there is still time for my exams to get over

i will work on the other issue till that time

**Comment by sk66641** [comment]
@aditya-bhaumik 
Ok
