### ISSUE TITLE
Improving UI/UX graphics of the website and the form submission since it covers the whole page and some portion of form isn't visible completely.

### ISSUE THREAD

**Issue by Khushipawar37** [sk66641/Random-Disco-Light-Simulator#92]
I will improve the graphics of website by adding cool hovering effects over the button and also improve the color combination and font of the website

**Comment by Khushipawar37** [comment]
Please assign it to me @sk66641 since people mostly get attracted by the graphics of website and I feel that I can make it look more better.

**Comment by Khushipawar37** [comment]
I will change that and also there is a bug that the footer disappears when light mode is switched on. So shall I fix it too @sk66641 ?

**Comment by sk66641** [comment]
@Khushipawar37 
it has been fixed

**Comment by Khushipawar37** [comment]
Sure, I will enhance it and add some hovering effects too
