### ISSUE TITLE
Feature: Playing music according to user's choice through youtube urls

### ISSUE THREAD

**Issue by ananya-dhiman** [sk66641/Random-Disco-Light-Simulator#94]
**Feature**
An audio player that takes a youtube URL input from the user and uses it to play that audio in the background on the disco page. If required it can be added as a drop-down box with high transparency to look appealing. 

**Demo Video**

https://github.com/sk66641/Random-Disco-Light-Simulator/assets/145692647/bda679ab-0c1f-4f83-ad60-cf4adb1fb809

(The audio crackling was because I was playing it on my Linux OS and won't be there in the final working)

GSSOC 2024

**Comment by Samik123Mit** [comment]
i will use and integrate apis to make sure that music comes from youtube ,pls assign me

**Comment by sk66641** [comment]
@ananya-dhiman 
Could you give an update over this issue as it has been pending for over two weeks?

**Comment by ananya-dhiman** [comment]
Yes the code is almost done and I will be making a pr soon. However right now the feature is limited and as mentioned it will be a good idea to add api to make it user friendly, so should I continue working with that or should I make the pr and create issue on enhance ment. Also I accidentally unassigned myself so can you assign me again.

**Comment by sk66641** [comment]
@ananya-dhiman 
as you can see there is already a feature to select music through urls but that doesn't work for youtube urls, you can upgrade that and it would be good if you continue working with adding api rather than creating another issue for the same.
