### ISSUE TITLE
Change the font-family of the page 

### ISSUE THREAD

**Issue by Sibam-Paul** [sk66641/Random-Disco-Light-Simulator#96]
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/158052549/38454e83-b0ea-4e18-aff9-4048e0272756)
I want to change  the font-family of the page to make it look appealing

_Please assign me this issue under GSSOC'24_

**Comment by shivathmikavemula** [comment]
please assign the task to me @sk66641

**Comment by sk66641** [comment]
@shivathmikavemula 
attach the screenshot, how will it look?
