### ISSUE TITLE
Update the Contributing.md with git commands and link it to read me 

### ISSUE THREAD

**Issue by Sibam-Paul** [sk66641/Random-Disco-Light-Simulator#97]
![image](https://github.com/sk66641/Random-Disco-Light-Simulator/assets/158052549/e0e16f41-0de3-483f-9929-b1fed401a940)
Will label git commands in palette format ND LINK THE CONTRIBUTING.md in Readme with a link to it

_Please assign me this in GSSOC'24_

**Comment by Sibam-Paul** [comment]
Please assign me this

**Comment by sk66641** [comment]
@Sibam-Paul 
Thank you for raising this issue. I've reviewed it, and it seems that no further action is needed at the moment. If you have any additional issues, feel free to reach out. 😊
